export const ERROR = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  FATAL_ERROR: 'FATAL_ERROR',
  ENTRY_EXISTS: 'ENTRY_EXISTS',
  ENTRY_NOT_FOUND: 'ENTRY_NOT_FOUND',
  AUTHORISATION_ERROR: 'AUTHORISATION_ERROR',
  AUTHENTICATION_ERROR: 'AUTHENTICATION_ERROR',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
};
